### PR TITLE
License change (BSD 3-clause to MPL 2.0)

### PR DESCRIPTION
**Pull request by IdkGoodName**
Changes license from BSD 3-clause license to Mozilla Public License 2.0

### CODE REVIEW

**Review by ItzNxthaniel — APPROVED** [review]
I approval of the License Change.

**Comment by ItzNxthaniel** [comment]
Contributors we also need approval from, but can't request reviews:

@bloomsirenix @Metalloriff

**Review by MasicoreLord — APPROVED** [review]
I approve of the License change

**Comment by MasicoreLord** [comment]
@bloomsirenix and @Metalloriff 
**[Possibly Last Chance]**
_Apologize for the annoyance/inconvenience of an extra notification on Github._
There needs to be an approval or disapproval on this change of license soon.

**Comment by Metalloriff** [comment]
QI am indifferent.

**Comment by ItzNxthaniel** [comment]
After a code audit, we realized responses from @bloomsirenix & @burritosoftware are no longer needed. Meaning this License Change can now be done.

**Pull request merged**
